#!/bin/bash
DN=$1
SCHID=$2
TMPPWD=$3

DEBIAN_FRONTEND=noninteractive apt-get install -y libnss-ldap nscd nss-updatedb libnss-db libpam-ccreds

cat > /etc/cron.hourly/nssupdate.sh << EOF
#!/bin/sh
nss_updatedb ldap
exit 0
EOF

chmod +x /etc/cron.hourly/nssupdate.sh

sed -i "/passwd:.*$/passwd: compat ldap" /etc/nsswitch.conf
sed -i "/group:.*$/passwd: compat ldap" /etc/nsswitch.conf
sed -i "/shadow:.*$/passwd: compat ldap" /etc/nsswitch.conf

cat > /etc/ldap.conf << EOF
base $DN
uri ldaps://ldap.$SCHID.cloudtop.ph
ldap_version 3
binddn cn=auth,$DN
bindpw $TMPPWD
rootbinddn cn=admin,$DN
pam_password md5
ssl on
tls_cacert /etc/ssl/certs/ldap.$SCHID.crt

nss_base_passwd        ou=users,$DN?one
nss_base_shadow        ou=users,$DN?one
nss_base_group         ou=roles,$DN?one
EOF

