#!/bin/bash
SCHID=$1
SCHNAME=$2
SCHDIV=$3
SCHREG=$4
TMPPWD=$5


if [ $# -ne 5 ]; then
	echo "Wrong number of arguments passed"
	exit
fi

DN="o=$1 $2,st=$3,l=$4,dc=cloudtop,dc=ph"

DEBIAN_FRONTEND=noninteractive apt-get install -y libnss-ldap nscd nss-updatedb libnss-db libpam-ccreds ldap-utils

cat > /etc/cron.hourly/nssupdate.sh << EOF
#!/bin/sh
nss_updatedb ldap
exit 0
EOF

chmod +x /etc/cron.hourly/nssupdate.sh

sed -i "s/passwd:.*$/passwd: compat ldap/g" /etc/nsswitch.conf
sed -i "s/group:.*$/group: compat ldap/g" /etc/nsswitch.conf
sed -i "s/shadow:.*$/shadow: compat ldap/g" /etc/nsswitch.conf

mv /etc/ldap.conf /etc/ldap.conf.bak
cat > /etc/ldap.conf << EOF
base $DN
uri ldaps://ldap.$SCHID.cloudtop.ph
ldap_version 3
binddn cn=auth,$DN
bindpw $TMPPWD
rootbinddn cn=admin,$DN
pam_password md5
ssl on
tls_cacert /etc/ssl/certs/ldap.$SCHID.crt

nss_base_passwd        ou=users,$DN?one
nss_base_shadow        ou=users,$DN?one
nss_base_group         ou=roles,$DN?one
EOF

mv /etc/ldap/ldap.conf /etc/ldap/ldap.conf.bak
ln -s /etc/ldap.conf /etc/ldap/ldap.conf

echo $TMPPWD > /etc/ldap.secret

timeout 5 openssl s_client -connect ldap.$SCHID.cloudtop.ph:636 -showcerts > /etc/ssl/certs/ldap.$SCHID.crt


mv /etc/pam.d/common-auth /etc/pam.d/common-auth.bak 
cat > /etc/pam.d/common-auth << EOF
#This configuration enables the use of LDAP and cached creds (ccreds) by PAM.
auth	[success=4 default=ignore]	pam_unix.so nullok_secure
auth	[success=3 default=ignore]	pam_ldap.so use_first_pass
auth	[success=2 default=ignore]	pam_ccreds.so minimum_uid=1000 action=validate use_first_pass
auth	[default=ignore]		pam_ccreds.so minimum_uid=1000 action=update
auth	requisite		pam_deny.so
auth	required			pam_permit.so
auth	optional			pam_ccreds.so minimum_uid=1000 action=store
auth	optional			pam_cap.so
EOF

mv /etc/pam.d/common-session /etc/pam.d/common-session.bak
cat > /etc/pam.d/common-session << EOF
session	[default=1]			pam_permit.so
session	requisite			pam_deny.so
session	required			pam_permit.so
session optional			pam_umask.so
session	required			pam_unix.so
session required	pam_mkhomedir.so skel=/etc/skel/ umask=0077 debug
session	optional			pam_ldap.so debug
session optional                        pam_ck_connector.so nox11
EOF

mv /etc/pam.d/common-session-noninteractive /etc/pam.d/common-session-noninteractive.bak
cat > /etc/pam.d/common-session-noninteractive << EOF
session	[default=1]			pam_permit.so
session	requisite			pam_deny.so
session	required			pam_permit.so
session optional			pam_umask.so
session	required	pam_unix.so 
session required	pam_mkhomedir.so skel=/etc/skel/ umask=0077 debug
session	optional			pam_ldap.so debug
EOF

nss_updatedb ldap

getent passwd

#reboot
if [ -z $(cat /etc/ssh/sshd_config | grep DenyGroups) ]; then
echo "DenyGroups teachers students" >> /etc/ssh/sshd_config
fi	
