#!/bin/bash

SCHID=$1
LOG="~/gatekeep_mgmt_$STAMP"

#Function for checking hostname
chkname(){
	
	echo -n "Checking if host name is in the proper format..."
	if [[ "$(hostname)" = "ldap.$SCHID.cloudtop.ph" ]]; then
		echo_success
		echo
		return 0
	else
		echo_failure
		echo
		return 1
	fi
}

#Function for checking if SSL certificate is present
chksslcert(){
	echo -n "Checking if SSL certificate exists..."
	if [ -z $(certutil -L -d /etc/openldap/certs) | grep "OpenLDAP Server") ]; then
		#echo "No certificate file found"
		echo_failed
		echo
		return 1
	else
		#echo "Certificate exists"
		echo_success
		echo
		return 0
	fi
}

#Function for checking if SSL cert can be retrieved over the network
chkssl(){
	echo -n "Checking if openssl connection to this VM works..."
	timeout 5 openssl s_client -connect ldap.$SCHID.cloudtop.ph:636 &> out
	ERR=$(cat out | grep err )
	
	if [ -z $ERR ]; then
		echo_success
		echo
		return 0
	else
		if [ -z $(echo $ERR | grep "self signed") ]; then
			echo_warning
			echo "Self-signed certificate must be replaced ASAP"
			return 0
		else
			echo_failure
			echo $ERR
			return 1
	fi
}

chksysconfigldap(){
	LDAPS=$(cat /etc/sysconfig/ldap|grep "SLAPD_LDAPS=yes")
	echo -n "Checking LDAPS..."
	if [ -z $LDAPS ]; then
		echo_success
		echo
	else
		echo_failure
		echo "LDAPS should be on"
		return 1
	fi
	
	LDAPS=$(cat /etc/sysconfig/ldap|grep "SLAPD_LDAP=no")
	if  [ -z $LDAP ]; then
		echo_success
		echo
	else
		echo_failure
		echo "LDAP should be off"
		return 1
	fi
}

chkldap(){
	slaptest -uv
	service slapd status
}

chkconfigldap(){
	
	echo -n "Checking if LDAP service is enabled on startup..."
	CHKCONFIG=$(chkconfig --list $srvc | gawk '{ print $4 }')
	if [ "$CHKCONFIG" = "2:on" ]; then
		echo_success
		echo
		return 0
	else
		echo_failure
		echo
		return 1
	fi
}

chkname
error $?

chksslcert
error $?

chkssl
error $?

chksysconfigldap
error $?

chkconfigldap
error $?





